# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ModuleA' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ModuleA
  pod 'CTMediator'
  
  pod 'ModuleC', :path =>'../../C'
  
  pod 'ModuleB', :path =>'../../B'

  target 'ModuleATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ModuleAUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
